spring:
  datasource:
         url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=round&autoReconnect=true
         username: root
         password: root
  redis:
     host: localhost
     port: 6379
     password: